name: Build and push docker images

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      container_registry_host:
        type: string
        required: true

      docker_image_name:
        type: string
        required: true

      dockerfile:
        type: string
        required: true
        default: Dockerfile

      dockerfile_context:
        type: string
        required: true
        default: '.'

      tag:
        type: string
        required: true

    secrets:
      container_registry_username:
        required: false

      container_registry_password:
        required: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ inputs.github_env  }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Azure Container Registry
        if: ${{ inputs.container_registry_username && inputs.container_registry_password }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.container_registry_host }}
          username: ${{ inputs.container_registry_username }}
          password: ${{ inputs.container_registry_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: '${{ inputs.container_registry_host }}/${{ inputs.docker_image_name }}'
          tags: |
            ${{ inputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerfile_context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
