name: Build and push docker images

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      docker_image_name:
        type: string
        required: true

      dockerfile:
        type: string
        required: true
        default: Dockerfile

      dockerfile_context:
        type: string
        required: true
        default: '.'

      tag:
        type: string
        required: true

      container_registry_server:
        type: string
        required: true

    secrets:
      container_registry_username:
        required: true

      container_registry_password:
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ inputs.github_env  }}

    env:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.container_registry_username }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.container_registry_password }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Azure Container Registry
        uses: docker/login-action@v2
        if: ${{ env.CONTAINER_REGISTRY_USERNAME != '' && env.CONTAINER_REGISTRY_PASSWORD != '' }}
        with:
          registry: ${{ inputs.container_registry_server }}
          username: ${{ secrets.container_registry_username }}
          password: ${{ secrets.container_registry_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: '${{ inputs.container_registry_server }}/${{ inputs.docker_image_name }}'
          tags: |
            ${{ inputs.tag }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerfile_context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
