name: RW — Change Azure postgres firewall rule

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      add_or_remove:
        type: string
        required: true

      database_resource_group:
        type: string
        required: true

      database_server_name:
        type: string
        required: true

      firewall_rule_name:
        type: string
        required: false
        default: github-runner

      is_single_server:
        type: string
        required: false
        default: 'false'

    secrets:
      azure_login_creds:
        required: true

defaults:
  run:
    shell: bash

jobs:
  change_firewall_rule:
    name: 'Change firewall rule'
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.github_env  }}

    steps:
      - uses: actions/checkout@v3

      - name: Get runner IP
        id: get-runner-ip
        run: |
          echo "runner_ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Echo Runner IP
        run: |
          echo "Runner IP: ${{ steps.get-runner-ip.outputs.runner_ip }}"

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: '${{ secrets.azure_login_creds }}'

      - name: Remove any previously created firewall rule (flexible server)
        if: ${{ inputs.is_single_server == 'false' }}
        continue-on-error: true
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az postgres flexible-server firewall-rule delete \
              --resource-group ${{ inputs.database_resource_group }} \
              --name ${{ inputs.database_server_name }} \
              --rule-name ${{ inputs.firewall_rule_name }} \
              --yes

      - name: Add firewall rule (flexible server)
        if: ${{ inputs.is_single_server == 'false' && inputs.add_or_remove == 'add' }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az postgres flexible-server firewall-rule create \
              --resource-group ${{ inputs.database_resource_group }} \
              --name ${{ inputs.database_server_name }} \
              --rule-name ${{ inputs.firewall_rule_name }} \
              --start-ip-address ${{ steps.get-runner-ip.outputs.runner_ip }}

      - name: Remove any previously created firewall rule (single server)
        if: ${{ inputs.is_single_server == 'true' }}
        continue-on-error: true
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az postgres server firewall-rule delete \
              --resource-group ${{ inputs.database_resource_group }} \
              --server-name ${{ inputs.database_server_name }} \
              --name ${{ inputs.firewall_rule_name }} \
              --yes

      - name: Add firewall rule (single server)
        if: ${{ inputs.is_single_server == 'true' && inputs.add_or_remove == 'add' }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az postgres server firewall-rule create \
              --resource-group ${{ inputs.database_resource_group }} \
              --server-name ${{ inputs.database_server_name }} \
              --name ${{ inputs.firewall_rule_name }} \
              --start-ip-address ${{ steps.get-runner-ip.outputs.runner_ip }} \
              --end-ip-address ${{ steps.get-runner-ip.outputs.runner_ip }}
