name: RW — Get a secret from a keyvault

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      keyvault:
        type: string
        required: true

      secret_ref:
        type: string
        required: true

      has_acl:
        type: boolean
        required: false
        default: false

    secrets:
      azure_login_creds:
        required: true

    outputs:
      result:
        description: 'The secret from the keyvault'
        value: ${{ jobs.get_secrets.outputs.result }}

defaults:
  run:
    shell: bash

jobs:
  get_secrets:
    name: 'Get the secret'
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get-secrets.outputs.result }}

    environment:
      name: ${{ inputs.github_env  }}

    steps:
      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: '${{ secrets.azure_login_creds }}'

      - name: Get runner IP
        if: ${{ inputs.has_acl }}
        id: get_runner_ip
        run: |
          echo "runner_ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Add runner to network ACL
        if: ${{ inputs.has_acl }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "Runner IP: ${{ steps.get_runner_ip.outputs.runner_ip }}"
            az keyvault network-rule add \
              --name ${{ inputs.keyvault }} \
              --ip-address ${{ steps.get_runner_ip.outputs.runner_ip }}

      - name: Get secrets
        id: get-secrets
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo \
            "result=$(az keyvault secret show \
            --vault-name ${{ inputs.keyvault }} \
            --name ${{ inputs.secret_ref }} | jq -r .value)" \
            >> $GITHUB_OUTPUT

      - name: Remove runner from network ACL
        if: ${{ inputs.has_acl }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az keyvault network-rule remove \
              --name ${{ inputs.keyvault }} \
              --ip-address ${{ steps.get_runner_ip.outputs.runner_ip }}
