name: Terraform Destroy

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      working_dir:
        type: string
        required: true

      tfvars_file:
        type: string
        required: true

      tf_backend_resource_group_name:
        type: string
        required: true

      tf_backend_storage_account_name:
        type: string
        required: true

      tf_backend_storage_container_name:
        type: string
        required: true

      tf_backend_state_key:
        type: string
        required: true

      tf_parallelism_count:
        type: string
        default: '10'

    secrets:
      arm_client_id:
        required: true

      arm_client_secret:
        required: true

      arm_subscription_id:
        required: true

      arm_tenant_id:
        required: true

env:
  ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
  ARM_CLIENT_SECRET: ${{ secrets.arm_client_secret }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.arm_subscription_id }}
  ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
  TF_BACKEND_RESOURCE_GROUP_NAME: ${{ inputs.tf_backend_resource_group_name }}
  TF_BACKEND_STORAGE_ACCOUNT_NAME: ${{ inputs.tf_backend_storage_account_name }}
  TF_BACKEND_STORAGE_CONTAINER_NAME: ${{ inputs.tf_backend_storage_container_name }}
  TF_BACKEND_STATE_KEY: ${{ inputs.tf_backend_state_key }}
  TFVARS_FILE: ${{ inputs.tfvars_file }}
  TF_PARALLELISM_COUNT: ${{ inputs.tf_parallelism_count }}
  WORKING_DIR: ${{ inputs.working_dir }}

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    environment:
      name: ${{ inputs.github_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
              -backend-config="resource_group_name=$TF_BACKEND_RESOURCE_GROUP_NAME" \
              -backend-config="storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT_NAME" \
              -backend-config="container_name=$TF_BACKEND_STORAGE_CONTAINER_NAME" \
              -backend-config="key=$TF_BACKEND_STATE_KEY"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=$TFVARS_FILE -parallelism=$TF_PARALLELISM_COUNT
